language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'
install:
  - pip install coveralls coverage
  - pip install -U setuptools
  - pip install pytest --upgrade
script:
  - pip install .
  - coverage run --source combojsonapi -m pytest -v
after_success:
  - coveralls
